sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        gOuEfAbJgALqs7Tl8BgvdcsORfH2e9EPdNT7pbBmD3Tor6ytBrtLvBv/Bi8RrXF5jIHBAlRmhXZdS5R8fqSCoSwETOO2rnyIszobA/29Dp5gPNPyYqjxN3EdqGeKc6yqEZ9WsXrfDzvmxhzIdYbQsuREg/1SMOEMtH7PmRVKzLRiHDSP/3TfJnodXPCRB/ATy14B/e1bqMUAfiapD5MbaWQ/240iBAIkbDHAiL7MD5uYZ79TChxXVFG4pe+C5bvWnhTQITCfH714dATAXvZGJuu5gSFlE9lxxqAq+BgH+UABD6zhUDMSBw4AtjacAgvbtDhbNk5pjJpCGmVZEhYERMaHP6Du1PyNuJNhgdd+dNpbBvcZzM955eUTcWTiKcp5yotnzb6VIFo2s044env9e7lud6v82wUbzGIPjXaPVWKnNpX5wZzDNWsHJm6tTf9AhRaP818/MTRhgau1XUmh0QvLgvR0aT9zoR9+fmQtfyAx3cHEi2f0A7fkNVPvoPGeW71fC+Vf+NkaUNeiaw5g/EAfJgovhP7D4UjXpJqRfNHFzp1pqr+ER8YGVc9UvOGgwnxbkfZCBVyjv+dodQy8eIhsHK8BBJs0ZLy1jTktLGmVdZEFugv7ch/u7MOauYRO2j0LcOvtPc668vl9yuvcRlzpv9IQ/7BGlcXiYCt3byQ=
    - secure: >-
        HlajCawbzebrEHHAGegXIOFrgKg8Yv5grrs3udocnpju419S2Yva729HDitnKXdoTjlDW1hhnaICg3m5wI1OlviBGR28hboLHbgbJkQ98jVzUXZdFyfp8N4Mja9pfZL4lYtKEXD5RROtqOW9yw0hFRVmby2NCPUm8gasDa5iMRfesmx6ghKCSb5JjUurO3xUVLYHQ2KQUOpE5ZByH2XyoY5+ffdpgt+2IwaUzoA40Q/s3h47e29oxyYc5c2LHYT4Hk++P3wuO3EVZ8Oy2IQG/RDM+3tnA+nfsKC0oE9SAaeQns8cZMXjyKc1P90cq2YW875QLjlC0umjyiFT9SJnIqR51XxFFaHQ0vSWg76OOCqv0DyMjOYr1OjVufTsSYTXgEeO2uA6gLrZ7JicLKvozSss615hkr4f/6wIK/oJA4MUTuFKf7p82EEeLrFYmxjaKju1bhIfXbeu7q5o8ah9RzXzeYuXWGZ9jfNsiYBnI7DKDH0aEigzUv7BfDG7P7KI3s6xz79/TK/8LjmrtB5GOm1h0444kU+G+DJwlJXHCninnAT8QDfxEbKw/EtkzeOwS+XvEE6Rz1MWYaEnfuG2vTYGplo+s4XrTDccWrh9n81vF9RILeenPjNil/yifQoe7OSNCEMezNtpF8xLiTBf/ICRCrdSqwtzL3/EMZ7pWtk=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
